version: "3.3"
services:
  boxfixer-agent:
    build: .
    image: boxfixer-agent:1.0
    container_name: boxfixer-agent
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/rmg/qa_credentials.yml:/etc/rmg/qa_credentials.yml